version: "3"

tasks:
  get:
    desc: Get flutter dependencies
    summary: |
      Get flutter dependencies
    cmds:
      - flutter pub get

  gen:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - dart run build_runner build -d
      -
  build:
    desc: Build apk release
    summary: |
      Run codegen
    cmds:
      - flutter build apk --release

  upgrade:
    desc: Upgrade flutter dependencies
    summary: |
      Run codegen
    cmds:
      - flutter pub upgrade --major-versions

  gen:clean:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - flutter clean
      - flutter pub get
      - dart run build_runner build -d

  gen:watch:
    desc: Generate dart files
    summary: |
      Watch codegen
    cmds:
      - dart run build_runner watch -d

  gen:tr:
    desc: Generate translations
    summary: |
      Run codegen
    cmds:
      - flutter gen-l10n