name: Build Flutter APK's and iPA files

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache CocoaPods dependencies
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          flutter-version: '3.32.5'
          cache: true

      - name: Setup Java
        continue-on-error: true
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --build-number=4
          flutter build apk --release --split-per-abi --target-platform=android-arm64 --build-number=3
          flutter build apk --release --split-per-abi --target-platform=android-arm --build-number=2
          flutter build apk --release --split-per-abi --target-platform=android-x64 --build-number=1

      - name: Build iPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r Laza-Ecommerce-${GITHUB_REF#refs/*/}.ipa Payload

      - name: Rename APK Files
        run: |
          cd build/app/outputs/flutter-apk
          mv app-armeabi-v7a-release.apk Laza-Ecommerce-${GITHUB_REF_NAME}-armeabi-v7a.apk
          mv app-arm64-v8a-release.apk Laza-Ecommerce-${GITHUB_REF_NAME}-arm64-v8a.apk
          mv app-x86_64-release.apk Laza-Ecommerce-${GITHUB_REF_NAME}-x86_64.apk
          mv app-release.apk Laza-Ecommerce-${GITHUB_REF_NAME}-universal.apk

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/ios/iphoneos/*.ipa"
          allowUpdates: true
